export const GET_AIRCRAFTS = "GET_AIRCRAFTS";
export const GET_ROUTES = "GET_ROUTES";
export const GET_AIRPORTS = "GET_AIRPORTS";
export const INIT = "INIT";
export const GET_CURRENT_SITUATION = "GET_CURRENT_SITUATION";